apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secret
            namespace: kube-system
            key: apiKey
      serviceUrl: >-
        https://f7c0f146-76b3-49ec-9169-01d98c8beac6.au-syd.secrets-manager.appdomain.cloud
